
export const ADD_SPOUSE_HEIR = 'ADD_SPOUSE_HEIR';
export const ADD_DESCENDANTS_HEIRS = 'ADD_DESCENDANTS_HEIRS';
export const SET_SPOUSE_HEIR = 'SET_SPOUSE_HEIR';
export const SET_DECEASED_GENDER = 'SET_DECEASED_GENDER';
export const SET_HEIR_NUMBERS = 'SET_HEIR_NUMBERS';
export const SET_CALCULATION_RESULT = 'SET_CALCULATION_RESULT';
export const SET_AMOUNT = 'SET_AMOUNT';

