
import { heirsEnum } from "../enums/heirs_enum";
// 20220702160159
// https://mirathapi.azurewebsites.net/api/DistributProbabilities/GetDatafromviewall
const AllData = [
  {
    "id": 1,
    "name": "husband",
    "ashabAlfarod": true,
    "propId": 1,
    "quota": 0.5,
    "causing": "حال عدم وجود الفرع الوارث",
    "causingEn": "In the absence of the inherited branch",
    "proofId": 1,
    "proofType": "قرأن",
    "noQVerse": "12        ",
    "surahQName": "النساء",
    "textAr": " وَلَكُمْ نِصْفُ مَا تَرَكَ أَزْوَاجُكُمْ إِنْ لَمْ يَكُنْ لَهُنَّ وَلَدٌ ۚ",
    "textEn": "You will inherit half of what your wives leave if they are childless",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 1,
    "name": "husband",
    "ashabAlfarod": true,
    "propId": 2,
    "quota": 0.25,
    "causing": "حال وجود الفرع الوارث",
    "causingEn": "If the inherited branch exists",
    "proofId": 2,
    "proofType": "قرأن",
    "noQVerse": "12        ",
    "surahQName": "النساء",
    "textAr": " وفَإِنْ كَانَ لَهُنَّ وَلَدٌ فَلَكُمُ الرُّبُعُ مِمَّا تَرَكْنَ ۚ",
    "textEn": " But if they have children, then ?your share is? one-fourth of the estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 2,
    "name": "wife",
    "ashabAlfarod": true,
    "propId": 3,
    "quota": 0.25,
    "causing": "حال عدم وجود الفرع الوارث",
    "causingEn": "In the absence of the inherited branch",
    "proofId": 3,
    "proofType": "قرأن",
    "noQVerse": "12        ",
    "surahQName": "النساء",
    "textAr": " وَلَكُمْ نِصْفُ مَا تَرَكَ أَزْوَاجُكُمْ إِنْ لَمْ يَكُنْ لَهُنَّ وَلَدٌ ۚ فَإِنْ كَانَ لَهُنَّ وَلَدٌ فَلَكُمُ الرُّبُعُ مِمَّا تَرَكْنَ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصِينَ بِهَا أَوْ دَيْنٍ ۚ وَلَهُنَّ الرُّبُعُ مِمَّا تَرَكْتُمْ إِنْ لَمْ يَكُنْ لَكُمْ وَلَدٌ ۚ فَإِنْ كَانَ لَكُمْ وَلَدٌ فَلَهُنَّ الثُّمُنُ مِمَّا تَرَكْتُمْ ۚ مِنْ بَعْدِ وَصِيَّةٍ تُوصُونَ بِهَا أَوْ دَيْنٍ ۗ وَإِنْ كَانَ رَجُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ فَلِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ ۚ فَإِنْ كَانُوا أَكْثَرَ مِنْ ذَٰلِكَ فَهُمْ شُرَكَاءُ فِي الثُّلُثِ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصَىٰ بِهَا أَوْ دَيْنٍ غَيْرَ مُضَارٍّ ۚ وَصِيَّةً مِنَ اللَّهِ ۗ وَاللَّهُ عَلِيمٌ حَلِيمٌ",
    "textEn": "You will inherit half of what your wives leave if they are childless. But if they have children, then ?your share is? one-fourth of the estate—after the fulfilment of bequests and debts. And your wives will inherit one-fourth of what you leave if you are childless. But if you have children, then your wives will receive one-eighth of your estate—after the fulfilment of bequests and debts. And if a man or a woman leaves neither parents nor children but only a brother or a sister ?from their mother’s side?, they will each inherit one-sixth, but if they are more than one, they ?all? will share one-third of the estate1—after the fulfilment of bequests and debts without harm ?to the heirs?.2 ?This is? a commandment from Allah. And Allah is All-Knowing, Most Forbearing.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 2,
    "name": "wife",
    "ashabAlfarod": true,
    "propId": 4,
    "quota": 0.125,
    "causing": "حال وجود الفرع الوارث",
    "causingEn": "If the inherited branch exists",
    "proofId": 4,
    "proofType": "قرأن",
    "noQVerse": "12        ",
    "surahQName": "النساء",
    "textAr": " وَلَكُمْ نِصْفُ مَا تَرَكَ أَزْوَاجُكُمْ إِنْ لَمْ يَكُنْ لَهُنَّ وَلَدٌ ۚ فَإِنْ كَانَ لَهُنَّ وَلَدٌ فَلَكُمُ الرُّبُعُ مِمَّا تَرَكْنَ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصِينَ بِهَا أَوْ دَيْنٍ ۚ وَلَهُنَّ الرُّبُعُ مِمَّا تَرَكْتُمْ إِنْ لَمْ يَكُنْ لَكُمْ وَلَدٌ ۚ فَإِنْ كَانَ لَكُمْ وَلَدٌ فَلَهُنَّ الثُّمُنُ مِمَّا تَرَكْتُمْ ۚ مِنْ بَعْدِ وَصِيَّةٍ تُوصُونَ بِهَا أَوْ دَيْنٍ ۗ وَإِنْ كَانَ رَجُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ فَلِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ ۚ فَإِنْ كَانُوا أَكْثَرَ مِنْ ذَٰلِكَ فَهُمْ شُرَكَاءُ فِي الثُّلُثِ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصَىٰ بِهَا أَوْ دَيْنٍ غَيْرَ مُضَارٍّ ۚ وَصِيَّةً مِنَ اللَّهِ ۗ وَاللَّهُ عَلِيمٌ حَلِيمٌ",
    "textEn": "You will inherit half of what your wives leave if they are childless. But if they have children, then ?your share is? one-fourth of the estate—after the fulfilment of bequests and debts. And your wives will inherit one-fourth of what you leave if you are childless. But if you have children, then your wives will receive one-eighth of your estate—after the fulfilment of bequests and debts. And if a man or a woman leaves neither parents nor children but only a brother or a sister ?from their mother’s side?, they will each inherit one-sixth, but if they are more than one, they ?all? will share one-third of the estate1—after the fulfilment of bequests and debts without harm ?to the heirs?.2 ?This is? a commandment from Allah. And Allah is All-Knowing, Most Forbearing.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 3,
    "name": "son",
    "ashabAlfarod": true,
    "propId": 5,
    "quota": 0.0,
    "causing": "فى حالة وجود فرع وارث مونث",
    "causingEn": "In the case of a branch inherited Month",
    "proofId": 5,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۚ فَإِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ وَإِنْ كَانَتْ وَاحِدَةً فَلَهَا النِّصْفُ ۚ وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ فَإِنْ لَمْ يَكُنْ لَهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِنْ كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصِي بِهَا أَوْ دَيْنٍ ۗ آبَاؤُكُمْ وَأَبْنَاؤُكُمْ لَا تَدْرُونَ أَيُّهُمْ أَقْرَبُ لَكُمْ نَفْعًا ۚ فَرِيضَةً مِنَ اللَّهِ ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا ",
    "textEn": "Allah commands you regarding your children: the share of the male will be twice that of the female",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 3,
    "name": "son",
    "ashabAlfarod": true,
    "propId": 6,
    "quota": 0.0,
    "causing": "فى حالة عدم وجود فرع وارث مونث",
    "causingEn": "In the absence of a branch inherited Month",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 4,
    "name": "daughter",
    "ashabAlfarod": true,
    "propId": 7,
    "quota": 0.5,
    "causing": "لانفرادها و عدم وجود عاصب",
    "causingEn": "For her alone and the absence of a nerve",
    "proofId": 7,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۚ فَإِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ وَإِنْ كَانَتْ وَاحِدَةً فَلَهَا النِّصْفُ ۚ وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ فَإِنْ لَمْ يَكُنْ لَهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِنْ كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصِي بِهَا أَوْ دَيْنٍ ۗ آبَاؤُكُمْ وَأَبْنَاؤُكُمْ لَا تَدْرُونَ أَيُّهُمْ أَقْرَبُ لَكُمْ نَفْعًا ۚ فَرِيضَةً مِنَ اللَّهِ ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا ",
    "textEn": "Allah commands you regarding your children: the share of the male will be twice that of the female",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 4,
    "name": "daughter",
    "ashabAlfarod": true,
    "propId": 8,
    "quota": 0.66,
    "causing": "لتعددهم وعدم وجود عاصب",
    "causingEn": "Because of their plurality and the absence of an asb",
    "proofId": 8,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " إِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ",
    "textEn": "If you leave only two ?or more? females, their share is two-thirds of the estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 4,
    "name": "daughter",
    "ashabAlfarod": true,
    "propId": 9,
    "quota": 0.0,
    "causing": "لوجود عاصب",
    "causingEn": "for having a nerve",
    "proofId": 9,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۚ",
    "textEn": "Allah commands you regarding your children: the share of the male will be twice that of the female",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 5,
    "name": "paternal_grand_son",
    "ashabAlfarod": true,
    "propId": 10,
    "quota": null,
    "causing": "يحجب بالابن الاعلى فى الدرجة",
    "causingEn": "Obscured by the son of the highest in class",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 5,
    "name": "paternal_grand_son",
    "ashabAlfarod": true,
    "propId": 11,
    "quota": 0.0,
    "causing": "فى حالة وجود فرع وارث مونث (من نفس الدرجة)",
    "causingEn": "In the case of a successor branch (of the same rank)",
    "proofId": 5,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۚ فَإِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ وَإِنْ كَانَتْ وَاحِدَةً فَلَهَا النِّصْفُ ۚ وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ فَإِنْ لَمْ يَكُنْ لَهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِنْ كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصِي بِهَا أَوْ دَيْنٍ ۗ آبَاؤُكُمْ وَأَبْنَاؤُكُمْ لَا تَدْرُونَ أَيُّهُمْ أَقْرَبُ لَكُمْ نَفْعًا ۚ فَرِيضَةً مِنَ اللَّهِ ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا ",
    "textEn": "Allah commands you regarding your children: the share of the male will be twice that of the female",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 5,
    "name": "paternal_grand_son",
    "ashabAlfarod": true,
    "propId": 12,
    "quota": 0.0,
    "causing": "فى حالة عدم وجود فرع وارث مونث (من نفس الدرجة)",
    "causingEn": "In the absence of a successor branch (of the same rank)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 6,
    "name": "paternal_grand_daughter",
    "ashabAlfarod": true,
    "propId": 13,
    "quota": 0.5,
    "causing": "لانفرادها و عدم وجود عاصب",
    "causingEn": "For her alone and the absence of a nerve",
    "proofId": 7,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۚ فَإِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ وَإِنْ كَانَتْ وَاحِدَةً فَلَهَا النِّصْفُ ۚ وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ فَإِنْ لَمْ يَكُنْ لَهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِنْ كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ ۚ مِنْ بَعْدِ وَصِيَّةٍ يُوصِي بِهَا أَوْ دَيْنٍ ۗ آبَاؤُكُمْ وَأَبْنَاؤُكُمْ لَا تَدْرُونَ أَيُّهُمْ أَقْرَبُ لَكُمْ نَفْعًا ۚ فَرِيضَةً مِنَ اللَّهِ ۗ إِنَّ اللَّهَ كَانَ عَلِيمًا حَكِيمًا ",
    "textEn": "Allah commands you regarding your children: the share of the male will be twice that of the female",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 6,
    "name": "paternal_grand_daughter",
    "ashabAlfarod": true,
    "propId": 14,
    "quota": 0.66,
    "causing": "لتعددهم وعدم وجود عاصب",
    "causingEn": "Because of their plurality and the absence of an asb",
    "proofId": 8,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " إِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ",
    "textEn": "If you leave only two ?or more? females, their share is two-thirds of the estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 6,
    "name": "paternal_grand_daughter",
    "ashabAlfarod": true,
    "propId": 15,
    "quota": 0.0,
    "causing": "عصبة بالغير ابن الابن من نفس الدرجة",
    "causingEn": "Clash with others, the son of the son of the same rank",
    "proofId": 9,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": " يُوصِيكُمُ اللَّهُ فِي أَوْلَادِكُمْ ۖ لِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۚ",
    "textEn": "Allah commands you regarding your children: the share of the male will be twice that of the female",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 6,
    "name": "paternal_grand_daughter",
    "ashabAlfarod": true,
    "propId": 16,
    "quota": 0.16,
    "causing": "لوجود بنت صلبية واحدة",
    "causingEn": "For having one solid girl",
    "proofId": 10,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "لِلِابْنَةِ النِّصْف، وَلِابْنَةِ الِابْنِ السُّدُس تَكْمِلَةَ الثُّلُثَيْنِ",
    "textEn": "And it was authenticated from him, peace be upon him, that he settled on a daughter, a son’s daughter, and a sister: that for a girl: half, and for a son’s daughter: a sixth, the completion of two-thirds, and the rest for the sister. Al-Bukhari included it in his Sahih.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 7,
    "name": "father",
    "ashabAlfarod": true,
    "propId": 18,
    "quota": 0.16,
    "causing": "لوجود الفرع الوارث المذكر",
    "causingEn": "For the presence of the masculine hereditary branch",
    "proofId": 11,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": "وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ\r\n",
    "textEn": "Each parent is entitled to one-sixth if you leave offspring.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 7,
    "name": "father",
    "ashabAlfarod": true,
    "propId": 19,
    "quota": 0.16,
    "causing": "لوجود الفرع الوارث المونث",
    "causingEn": "For the existence of the inherited male branch",
    "proofId": 11,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": "وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ\r\n",
    "textEn": "Each parent is entitled to one-sixth if you leave offspring.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 7,
    "name": "father",
    "ashabAlfarod": true,
    "propId": 20,
    "quota": null,
    "causing": "عدم وجود الفرع الوارث المذكر",
    "causingEn": "Absence of the masculine hereditary branch",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 8,
    "name": "mother",
    "ashabAlfarod": true,
    "propId": 21,
    "quota": 0.16,
    "causing": "لوجود الفرع الوارث أو عدد من الاخوة",
    "causingEn": "For the existence of the inherited branch or a number of brothers",
    "proofId": 12,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": "وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ فَإِنْ لَمْ يَكُنْ لَهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِنْ كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ ",
    "textEn": "Each parent is entitled to one-sixth if you leave offspring.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 8,
    "name": "mother",
    "ashabAlfarod": true,
    "propId": 22,
    "quota": 0.33,
    "causing": "لعدم وجود فرع وارث وعدم وجود عدد من الاخوة",
    "causingEn": "The absence of an inheriting branch and the absence of a number of brothers",
    "proofId": 12,
    "proofType": "قرأن",
    "noQVerse": "11        ",
    "surahQName": "النساء",
    "textAr": "وَلِأَبَوَيْهِ لِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ مِمَّا تَرَكَ إِنْ كَانَ لَهُ وَلَدٌ ۚ فَإِنْ لَمْ يَكُنْ لَهُ وَلَدٌ وَوَرِثَهُ أَبَوَاهُ فَلِأُمِّهِ الثُّلُثُ ۚ فَإِنْ كَانَ لَهُ إِخْوَةٌ فَلِأُمِّهِ السُّدُسُ ",
    "textEn": "Each parent is entitled to one-sixth if you leave offspring.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 8,
    "name": "mother",
    "ashabAlfarod": true,
    "propId": 23,
    "quota": 0.0,
    "causing": "المسألة العمرية لانحصار التركة فى أب و أم و أحد الزوجين",
    "causingEn": "The issue of age because the estate is confined to a father, a mother, and one of the spouses",
    "proofId": 13,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "المسالة العمرية 1",
    "textEn": null,
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 12,
    "name": "full_brother",
    "ashabAlfarod": false,
    "propId": 28,
    "quota": 0.0,
    "causing": "عصبة بالنفس (حال عدم وجود الاب أو الفرع الوارث المذكر)",
    "causingEn": "Asbah of the soul (in the absence of the father or masculine hereditary offspring)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 14,
    "name": "maternal_sibling",
    "ashabAlfarod": true,
    "propId": 32,
    "quota": 0.16,
    "causing": "حال انفراده وعدم وجود من يحجبه",
    "causingEn": "When he is alone and there is no one to block him",
    "proofId": 14,
    "proofType": "قرأن",
    "noQVerse": "12        ",
    "surahQName": "النساء",
    "textAr": "وَإِنْ كَانَ رَجُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ فَلِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ ۚ ",
    "textEn": "And if a man or a woman leaves neither parents nor children but only a brother or a sister ?from their mother’s side?, they will each inherit one-sixth, but if they are more than one, they ?all? will share one-third of the estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 14,
    "name": "maternal_sibling",
    "ashabAlfarod": true,
    "propId": 33,
    "quota": 0.33,
    "causing": "حال تعددهم و عدم وجود حاجب",
    "causingEn": "If they are many and there is no eyebrow",
    "proofId": 15,
    "proofType": "قرأن",
    "noQVerse": "12        ",
    "surahQName": "النساء",
    "textAr": "ۗ وَإِنْ كَانَ رَجُلٌ يُورَثُ كَلَالَةً أَوِ امْرَأَةٌ وَلَهُ أَخٌ أَوْ أُخْتٌ فَلِكُلِّ وَاحِدٍ مِنْهُمَا السُّدُسُ ۚ فَإِنْ كَانُوا أَكْثَرَ مِنْ ذَٰلِكَ فَهُمْ شُرَكَاءُ فِي الثُّلُثِ ۚ ",
    "textEn": "And if a man or a woman leaves neither parents nor children but only a brother or a sister ?from their mother’s side?, they will each inherit one-sixth, but if they are more than one, they ?all? will share one-third of the estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 15,
    "name": "full_sister",
    "ashabAlfarod": true,
    "propId": 38,
    "quota": 0.5,
    "causing": "حال انفراها و عدم وجود أخ شقيق",
    "causingEn": "In the case of their separation and the absence of a brother, a brother",
    "proofId": 16,
    "proofType": "قرأن",
    "noQVerse": "176       ",
    "surahQName": "النساء",
    "textAr": "يَسْتَفْتُونَكَ قُلِ اللَّهُ يُفْتِيكُمْ فِي الْكَلَالَةِ ۚ إِنِ امْرُؤٌ هَلَكَ لَيْسَ لَهُ وَلَدٌ وَلَهُ أُخْتٌ فَلَهَا نِصْفُ مَا تَرَكَ ۚ ",
    "textEn": "If a man dies childless and leaves behind a sister, she will inherit one-half of his estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 15,
    "name": "full_sister",
    "ashabAlfarod": true,
    "propId": 39,
    "quota": 0.66,
    "causing": "لتعددهم و عدم وجود أخ شقيق",
    "causingEn": "Because of their plurality and the absence of a brother-in-law",
    "proofId": 17,
    "proofType": "قرأن",
    "noQVerse": "176       ",
    "surahQName": "النساء",
    "textAr": "يَسْتَفْتُونَكَ قُلِ اللَّهُ يُفْتِيكُمْ فِي الْكَلَالَةِ ۚ إِنِ امْرُؤٌ هَلَكَ لَيْسَ لَهُ وَلَدٌ وَلَهُ أُخْتٌ فَلَهَا نِصْفُ مَا تَرَكَ ۚ وَهُوَ يَرِثُهَا إِنْ لَمْ يَكُنْ لَهَا وَلَدٌ ۚ فَإِنْ كَانَتَا اثْنَتَيْنِ فَلَهُمَا الثُّلُثَانِ مِمَّا تَرَكَ ۚ ",
    "textEn": "If this person leaves behind two sisters, they together will inherit two-thirds of the estate.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 15,
    "name": "full_sister",
    "ashabAlfarod": true,
    "propId": 40,
    "quota": 0.0,
    "causing": "عصبة بالغير مع الاخ الشقيق",
    "causingEn": "Band with others with the brother brother",
    "proofId": 18,
    "proofType": "قرأن",
    "noQVerse": "176       ",
    "surahQName": "النساء",
    "textAr": "يَسْتَفْتُونَكَ قُلِ اللَّهُ يُفْتِيكُمْ فِي الْكَلَالَةِ ۚ إِنِ امْرُؤٌ هَلَكَ لَيْسَ لَهُ وَلَدٌ وَلَهُ أُخْتٌ فَلَهَا نِصْفُ مَا تَرَكَ ۚ وَهُوَ يَرِثُهَا إِنْ لَمْ يَكُنْ لَهَا وَلَدٌ ۚ فَإِنْ كَانَتَا اثْنَتَيْنِ فَلَهُمَا الثُّلُثَانِ مِمَّا تَرَكَ ۚ وَإِنْ كَانُوا إِخْوَةً رِجَالًا وَنِسَاءً فَلِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۗ ",
    "textEn": "if the deceased leaves male and female siblings, a male’s share will be equal to that of two females.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 15,
    "name": "full_sister",
    "ashabAlfarod": true,
    "propId": 41,
    "quota": 0.0,
    "causing": "عصبة مع الفرع الوارث المونث",
    "causingEn": "League with the inherited male branch",
    "proofId": 19,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "للبنت النصف وبنت الابن السدس تكملة الثلثين، والباقي للأخت تعصيباً",
    "textEn": "And it was authenticated from him, peace be upon him, that he settled on a daughter, a son’s daughter, and a sister: that for a girl: half, and for a son’s daughter: a sixth, the completion of two-thirds, and the rest for the sister. Al-Bukhari included it in his Sahih.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 16,
    "name": "paternal_sister",
    "ashabAlfarod": true,
    "propId": 43,
    "quota": 0.5,
    "causing": "حال انفراها و عدم وجود أخ لآب",
    "causingEn": "If they are separated and there is no father`s brother",
    "proofId": 16,
    "proofType": "قرأن",
    "noQVerse": "176       ",
    "surahQName": "النساء",
    "textAr": "يَسْتَفْتُونَكَ قُلِ اللَّهُ يُفْتِيكُمْ فِي الْكَلَالَةِ ۚ إِنِ امْرُؤٌ هَلَكَ لَيْسَ لَهُ وَلَدٌ وَلَهُ أُخْتٌ فَلَهَا نِصْفُ مَا تَرَكَ ۚ ",
    "textEn": "If a man dies childless and leaves behind a sister, she will inherit one-half of his estate",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 16,
    "name": "paternal_sister",
    "ashabAlfarod": true,
    "propId": 44,
    "quota": 0.66,
    "causing": "لتعددهم و عدم وجود أخ لآب",
    "causingEn": "Because of their plurality and the absence of a brother to a father",
    "proofId": 17,
    "proofType": "قرأن",
    "noQVerse": "176       ",
    "surahQName": "النساء",
    "textAr": "يَسْتَفْتُونَكَ قُلِ اللَّهُ يُفْتِيكُمْ فِي الْكَلَالَةِ ۚ إِنِ امْرُؤٌ هَلَكَ لَيْسَ لَهُ وَلَدٌ وَلَهُ أُخْتٌ فَلَهَا نِصْفُ مَا تَرَكَ ۚ وَهُوَ يَرِثُهَا إِنْ لَمْ يَكُنْ لَهَا وَلَدٌ ۚ فَإِنْ كَانَتَا اثْنَتَيْنِ فَلَهُمَا الثُّلُثَانِ مِمَّا تَرَكَ ۚ ",
    "textEn": "If this person leaves behind two sisters, they together will inherit two-thirds of the estate.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 16,
    "name": "paternal_sister",
    "ashabAlfarod": true,
    "propId": 45,
    "quota": 0.0,
    "causing": "عصبة بالغير مع الاخ لآب",
    "causingEn": "Band with others with brother Labe",
    "proofId": 18,
    "proofType": "قرأن",
    "noQVerse": "176       ",
    "surahQName": "النساء",
    "textAr": "يَسْتَفْتُونَكَ قُلِ اللَّهُ يُفْتِيكُمْ فِي الْكَلَالَةِ ۚ إِنِ امْرُؤٌ هَلَكَ لَيْسَ لَهُ وَلَدٌ وَلَهُ أُخْتٌ فَلَهَا نِصْفُ مَا تَرَكَ ۚ وَهُوَ يَرِثُهَا إِنْ لَمْ يَكُنْ لَهَا وَلَدٌ ۚ فَإِنْ كَانَتَا اثْنَتَيْنِ فَلَهُمَا الثُّلُثَانِ مِمَّا تَرَكَ ۚ وَإِنْ كَانُوا إِخْوَةً رِجَالًا وَنِسَاءً فَلِلذَّكَرِ مِثْلُ حَظِّ الْأُنْثَيَيْنِ ۗ ",
    "textEn": "if the deceased leaves male and female siblings, a male’s share will be equal to that of two females.",
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 16,
    "name": "paternal_sister",
    "ashabAlfarod": true,
    "propId": 46,
    "quota": 0.16,
    "causing": "تكملة للثلثين مع الاخت الشقيقة وعدم وجود الفرع الوارث المونث أو الاخ لآب",
    "causingEn": "Supplementation of two-thirds with the full sister and the absence of the inherited male branch or the father`s brother",
    "proofId": 20,
    "proofType": "قرأن",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "القياس على حالة ميراث بنت الابن للسدس مع البنت تكملة للثلثين ( فَإِنْ كُنَّ نِسَاءً فَوْقَ اثْنَتَيْنِ فَلَهُنَّ ثُلُثَا مَا تَرَكَ ۖ  )",
    "textEn": null,
    "proofTypeEn": "Quran",
    "surahQNameEn": "Surat Al Nisaa"
  },
  {
    "id": 16,
    "name": "paternal_sister",
    "ashabAlfarod": true,
    "propId": 47,
    "quota": 0.0,
    "causing": "عصبة مع الغير الفرع الوارث المونث",
    "causingEn": "League with others",
    "proofId": 21,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أجعلوا الاخوات مع البنات عصبة ",
    "textEn": "Make girls with sisters ?Asabah",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 18,
    "name": "full_nephew",
    "ashabAlfarod": false,
    "propId": 49,
    "quota": null,
    "causing": "حالة عدم وجود اى من (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر (الاب) - الاخ الشقيق - الاخ لآب)",
    "causingEn": "In the absence of any of the (masculine inheriting offspring (son) - descent masculine inheritor (father) - full brother - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 18,
    "name": "full_nephew",
    "ashabAlfarod": false,
    "propId": 50,
    "quota": null,
    "causing": "اذا كانت معه بنت اخ شقيق وعدم وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر (الاب) - الاخ الشقيق - الاخ لآب)",
    "causingEn": "If he has a niece, a full-brother, and he does not have any of the (masculine inheriting offspring (son) - descent, masculine heir (father) - full brother - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 18,
    "name": "full_nephew",
    "ashabAlfarod": false,
    "propId": 51,
    "quota": 0.0,
    "causing": " حال وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر (الاب) - الاخ الشقيق - الاخ لآب)",
    "causingEn": "If any of the (masculine hereditary offspring (son) - masculine hereditary descent (father) - full brother - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 19,
    "name": "paternal_nephew",
    "ashabAlfarod": false,
    "propId": 52,
    "quota": null,
    "causing": "حالة عدم وجود اى من (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر (الاب) - الاخ الشقيق - ابن الاخ الشقيق- الاخ لآب)",
    "causingEn": "In the absence of any of the (masculine inheriting offspring (son) - ancestor masculine inheritor (father) - full brother - son of the full brother - father`s brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 19,
    "name": "paternal_nephew",
    "ashabAlfarod": false,
    "propId": 53,
    "quota": null,
    "causing": "اذا كانت معه بنت اخ لآب وعدم وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر (الاب) - الاخ الشقيق - ابن الاخ الشقيق - الاخ لآب)",
    "causingEn": "If he has a daughter with a paternal brother and the absence of any of the (masculine inheriting offspring (son) - descent masculine inheritor (father) - full brother - nephew of the full brother - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 19,
    "name": "paternal_nephew",
    "ashabAlfarod": false,
    "propId": 54,
    "quota": 0.0,
    "causing": " حال وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر (الاب) - الاخ الشقيق - ابن الاخ الشقيق - الاخ لآب)",
    "causingEn": "If any of the (masculine hereditary offspring (son) - ancestor masculine inheritor (father) - full brother - son of the full brother - father`s brother )",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 20,
    "name": "full_paternal_uncle",
    "ashabAlfarod": false,
    "propId": 55,
    "quota": null,
    "causing": "حالة عدم وجود اى من (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر مطلقا - الاخ الشقيق - الاخ لآب)",
    "causingEn": "In the absence of any of the (masculine inheriting offspring (son) - masculine inheriting descent at all - full brother - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 20,
    "name": "full_paternal_uncle",
    "ashabAlfarod": false,
    "propId": 56,
    "quota": 0.0,
    "causing": " حال وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر المطلق - الاخ الشقيق - الاخ لآب)",
    "causingEn": "In the event of any of the (masculine inheriting offspring (son) - ancestor of the absolute masculine inheritor - full brother - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 21,
    "name": "paternal_paternal_uncle",
    "ashabAlfarod": false,
    "propId": 57,
    "quota": null,
    "causing": "حالة عدم وجود اى من (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر مطلقا - الاخ الشقيق - العم الشقيق- الاخ لآب)",
    "causingEn": "In the absence of any of the (masculine inheriting offspring (son) - masculine hereditary ancestry at all - full brother - brotherly uncle - paternal brother)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 21,
    "name": "paternal_paternal_uncle",
    "ashabAlfarod": false,
    "propId": 58,
    "quota": 0.0,
    "causing": " حال وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر المطلق - الاخ الشقيق - الاخ لآب - العم الشقيق)",
    "causingEn": "In the event of any of the (masculine inheriting offspring (son) - ancestor hereditary masculine absolute - full brother - paternal brother - brotherly uncle)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 22,
    "name": "full_cousin",
    "ashabAlfarod": false,
    "propId": 59,
    "quota": null,
    "causing": "حالة عدم وجود اى من (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر مطلقا - الاخ الشقيق - العم الشقيق- العم لآب)",
    "causingEn": "In the absence of any of the (masculine inheriting offspring (son) - masculine hereditary ancestry at all - full brother - brotherly uncle - paternal uncle)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 22,
    "name": "full_cousin",
    "ashabAlfarod": false,
    "propId": 60,
    "quota": 0.0,
    "causing": " حال وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر المطلق - الاخ الشقيق - الاخ لآب - العم الشقيق - العم لاب)",
    "causingEn": "In the event of any of the (masculine inheriting offspring (son) - ancestor hereditary masculine absolute - full brother - paternal brother - brotherly uncle - paternal uncle)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 23,
    "name": "paternal_cousin",
    "ashabAlfarod": false,
    "propId": 61,
    "quota": null,
    "causing": "حالة عدم وجود اى من (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر مطلقا - الاخ الشقيق - العم الشقيق- الاخ لآب -  العم الشقيق)",
    "causingEn": "In the absence of any of the (masculine inheriting offspring (son) - masculine hereditary ancestry at all - full brother - full uncle - paternal brother - full uncle)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 23,
    "name": "paternal_cousin",
    "ashabAlfarod": false,
    "propId": 62,
    "quota": 0.0,
    "causing": " حال وجود أى من  (الفرع الوارث المذكر (الابن)- الاصل الوارث المذكر المطلق - الاخ الشقيق - الاخ لآب - العم الشقيق -  ابن العم الشقيق)",
    "causingEn": "If any of the (masculine hereditary offspring (son) - ancestor hereditary masculine absolute - full brother - paternal brother - brotherly uncle - brotherly cousin)",
    "proofId": 6,
    "proofType": "حديث",
    "noQVerse": null,
    "surahQName": null,
    "textAr": "أَلْحِقُوا الْفَرَائِضَ بِأَهْلِهَا، فَمَا بَقِيَ فَهُوَ لِأَوْلَى رَجُلٍ ذَكَرٍ",
    "textEn": "attach the statutes to its people, and whatever remains is for the first male man.",
    "proofTypeEn": "Hadith",
    "surahQNameEn": null
  },
  {
    "id": 9,
    "name": "paternal_grand_father",
    "ashabAlfarod": false,
    "propId": 63,
    "quota": 0.16,
    "causing": "وجود الاب او الفرع الوارث المذكر\r\nلعدم ",
    "causingEn": "Presence of a paternal or masculine hereditary offspring",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  },
  {
    "id": 9,
    "name": "paternal_grand_father",
    "ashabAlfarod": false,
    "propId": 64,
    "quota": 0.16,
    "causing": "لعدم وجود الاب الفرع الوارث المونث\r\n",
    "causingEn": "For the absence of a father the inherited branch of the genus",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  },
  {
    "id": 9,
    "name": "paternal_grand_father",
    "ashabAlfarod": false,
    "propId": 65,
    "quota": 0.0,
    "causing": "حال وجود الاب\r\n",
    "causingEn": "If there is a father",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  },
  {
    "id": 10,
    "name": "paternal_grand_mother",
    "ashabAlfarod": false,
    "propId": 66,
    "quota": 0.16,
    "causing": "حال عدم وجود الاب والام",
    "causingEn": "If there is no father and mother",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  },
  {
    "id": 10,
    "name": "paternal_grand_mother",
    "ashabAlfarod": false,
    "propId": 67,
    "quota": 0.12,
    "causing": "حال عدم وجود الاب والام و حال وجود جدة لام شركاء فى السدس",
    "causingEn": "In the absence of the father and mother, and in the event of the presence of the mother’s grandmother, partners in the sixth",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  },
  {
    "id": 11,
    "name": "maternal_grand_mother",
    "ashabAlfarod": false,
    "propId": 68,
    "quota": 0.16,
    "causing": "حال عدم وجود والام",
    "causingEn": "If there is no mother",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  },
  {
    "id": 11,
    "name": "maternal_grand_mother",
    "ashabAlfarod": false,
    "propId": 69,
    "quota": 0.12,
    "causing": "حال عدم وجود الاب والام و حال وجود جدة لام شركاء فى السدس",
    "causingEn": "In the absence of the father and mother, and in the event of the presence of the mother’s grandmother, partners in the sixth",
    "proofId": 22,
    "proofType": null,
    "noQVerse": null,
    "surahQName": null,
    "textAr": "الاجماع",
    "textEn": null,
    "proofTypeEn": "",
    "surahQNameEn": null
  }
]
export default AllData;